### ISSUE TITLE
Migrating from vaerh provider, issue with bridge

### ISSUE THREAD

**Issue by durandguru** [GNewbury1/terraform-provider-routeros#104]
**Describe the bug**
I used the @vaerh provider before and want to switch to this one after the merge. If I only replace the provider and run a plan. It wants to create a new bridge.

**To Reproduce**
Current setup in vaerh provider:
resource "routeros_bridge" "bridge" {
  name              = "bridge"
  ingress_filtering = true
  priority          = "0x3000"
  vlan_filtering    = true
}

Switch providers and run plan

 # routeros_bridge.bridge will be created
  + resource "routeros_bridge" "bridge" {
      + actual_mtu          = (known after apply)
      + admin_mac           = (known after apply)
      + ageing_time         = "5m"
      + arp                 = "enabled"
      + arp_timeout         = "auto"
      + auto_mac            = true
      + disabled            = false
      + ether_type          = "0x8100"
      + fast_forward        = (known after apply)
      + forward_delay       = "15s"
      + frame_types         = "admit-all"
      + id                  = (known after apply)
      + igmp_snooping       = false
      + ingress_filtering   = true
      + l2mtu               = (known after apply)
      + mac_address         = (known after apply)
      + max_message_age     = "20s"
      + mtu                 = "auto"
      + name                = "bridge"
      + priority            = "0x3000"
      + protocol_mode       = "rstp"
      + pvid                = 1
      + running             = (known after apply)
      + transmit_hold_count = 6
      + vlan_filtering      = true
    }

**Expected behavior**
Just migrate

**Additional context**

**Comment by vaerh** [comment]
Can you test this solution?
https://developer.hashicorp.com/terraform/cli/commands/state/replace-provider
And please save your state file before that.

**Comment by durandguru** [comment]
The same issue. The other resources managed in this project has no problems.
I performed terraform state replace-provider vaerh/routeros GNewbury1/routeros

**Comment by GNewbury1** [comment]
Yep, I think #103 created a breaking change, but was tagged as a patch version rather than major 🤦 Sorry, that's my mistake.

@durandguru for the time being, can you test with v1.0.2 instead of v1.0.3, and see if that works?

@vaerh I'll leave my pull requests open in the future until we've both reviewed them. I really should have spotted this

**Comment by durandguru** [comment]
1.0.2 works
