### ISSUE TITLE
Bridge and IGMP setting

### ISSUE THREAD

**Issue by durandguru** [GNewbury1/terraform-provider-routeros#106]
**Describe the bug**
I enable IGMP on the bridge. After apply I get an error about MikrotikResourceDataToTerraform

**To Reproduce**
resource "routeros_bridge" "bridge" {
  name              = "bridge"
  ingress_filtering = true
  protocol_mode     = "rstp"
  priority          = "0x3000"
  igmp_snooping     = true
  vlan_filtering    = true
}

**Expected behavior**

**Additional context**
Error
│ Warning: Field not found
│
│   with routeros_bridge.bridge,
│   on ports.tf line 1, in resource "routeros_bridge" "bridge":
│    1: resource "routeros_bridge" "bridge" {
│
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: igmp_version <<<= 2

**Comment by durandguru** [comment]
Second error 
│ Warning: Field not found
│
│   with routeros_bridge.bridge,
│   on ports.tf line 1, in resource "routeros_bridge" "bridge":
│    1: resource "routeros_bridge" "bridge" {
│
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: last_member_query_count <<<= 2

**Comment by durandguru** [comment]
![image](https://user-images.githubusercontent.com/79765683/219466233-a1183b55-bfcc-49a0-a8a9-63029e28e8db.png)
 I Think al these are not in the bridge setting

**Comment by vaerh** [comment]
Wow, this menu appears after enabling IGMP, I did not see it when implementing a bridge interface and it will need to be added.

**Comment by GNewbury1** [comment]
Yep, here's the different between the API objects for two bridges - one has IGMP snooping enabled, the other doesn't:
```json
[
  {
    ".id": "*2",
    "actual-mtu": "1500",
    "ageing-time": "5m",
    "arp": "enabled",
    "arp-timeout": "auto",
    "auto-mac": "true",
    "dhcp-snooping": "false",
    "disabled": "false",
    "fast-forward": "true",
    "forward-delay": "15s",
    "igmp-snooping": "false",
    "l2mtu": "65535",
    "mac-address": "FE:F3:52:67:CA:3A",
    "max-message-age": "20s",
    "mtu": "auto",
    "name": "bridge",
    "priority": "0x8000",
    "protocol-mode": "rstp",
    "running": "true",
    "transmit-hold-count": "6",
    "vlan-filtering": "false"
  },
  {
    ".id": "*4",
    "actual-mtu": "1500",
    "ageing-time": "5m",
    "arp": "enabled",
    "arp-timeout": "auto",
    "auto-mac": "true",
    "dhcp-snooping": "false",
    "disabled": "false",
    "fast-forward": "false",
    "forward-delay": "15s",
    "igmp-snooping": "true",
    "igmp-version": "2",
    "l2mtu": "65535",
    "last-member-interval": "1s",
    "last-member-query-count": "2",
    "mac-address": "7E:5F:A1:0E:25:56",
    "max-message-age": "20s",
    "membership-interval": "4m20s",
    "mld-version": "1",
    "mtu": "auto",
    "multicast-querier": "false",
    "multicast-router": "temporary-query",
    "name": "bridge-lan",
    "priority": "0x8000",
    "protocol-mode": "rstp",
    "querier-interval": "4m15s",
    "query-interval": "2m5s",
    "query-response-interval": "10s",
    "running": "true",
    "startup-query-count": "2",
    "startup-query-interval": "31s250ms",
    "transmit-hold-count": "6",
    "vlan-filtering": "false"
  }
]
```

I just tested setting one of the extra fields on a bridge that _doesn't_ have IGMP snooping enabled, and it seems the API ignores it:
```
❯ curl -k -X PATCH -d '{"multicast-querier":"false"}' -H "content-type: application/json" https://localhost/rest/interface/bridge/\*2 -u admin
Enter host password for user 'admin':
{".id":"*2","actual-mtu":"1500","ageing-time":"5m","arp":"enabled","arp-timeout":"auto","auto-mac":"true","dhcp-snooping":"false","disabled":"false","fast-forward":"true","forward-delay":"15s","igmp-snooping":"false","l2mtu":"65535","mac-address":"FE:F3:52:67:CA:3A","max-message-age":"20s","mtu":"auto","name":"bridge","priority":"0x8000","protocol-mode":"rstp","running":"true","transmit-hold-count":"6","vlan-filtering":"false"
```

The only bad thing about this is if someone sets one of these igmp fields without actually enabling igmp snooping, Terraform will think it was successful and update the state.  Additionally, I don't know of a way to enable/disable fields based on the value of another.

**Comment by vaerh** [comment]
Wait a bit, I'm preparing patches for this.

**Comment by vaerh** [comment]
> The only bad thing about this is if someone sets one of these igmp fields without actually enabling igmp snooping, Terraform will think it was successful and update the state. Additionally, I don't know of a way to enable/disable fields based on the value of another.

Yes, this is predictable behavior, but I don't see a problem with it yet (storing dummy properties in the TF state file).
You can use predefined [SDKv2 validators](https://developer.hashicorp.com/terraform/plugin/framework/migrating/attributes-blocks/validators-predefined) to control when creating a plan, but they do not allow you to control incorrect behavior if, for example, snooping is disabled and there are properties related to it.

>   igmp_snooping  = false
>   igmp_version   = 3

**Comment by vaerh** [comment]
@durandguru Please check the fixes [v1.0.7](https://github.com/GNewbury1/terraform-provider-routeros/releases/tag/v1.0.7)

**Comment by durandguru** [comment]
in 1.0.8

│ Warning: Field not found
│
│   with routeros_bridge.bridge,
│   on ports.tf line 1, in resource "routeros_bridge" "bridge":
│    1: resource "routeros_bridge" "bridge" {
│
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: multicast_router <<<=
│ temporary-query

**Comment by vaerh** [comment]
Hmm, I thought I found all the fields according to the documentation 😕. Please show your bridge section from the TF file.

**Comment by durandguru** [comment]
resource "routeros_bridge" "bridge" {
  name              = "bridge"
  ingress_filtering = true
  protocol_mode     = "rstp"
  priority          = "0x1000"
  igmp_snooping     = true
  vlan_filtering    = true
}

I just use the default values from mikrotik for igmp.

**Comment by durandguru** [comment]
@vaerh tested 1.0.9 and got this error:

│ Error: InternalValidate
│
│   with provider["registry.terraform.io/gnewbury1/routeros"],
│   on provider.tf line 1, in provider "routeros":
│    1: provider "routeros" {
│
│ Internal validation of the provider failed! This is always a bug
│ with the provider itself, and not a user issue. Please report
│ this bug:
│
│ 2 errors occurred:
│       * resource routeros_bridge: multicast_router: Default must be nil if computed
│       * resource routeros_interface_bridge: multicast_router: Default must be nil if computed

**Comment by vaerh** [comment]
I'm sorry, I've corrected the error.

**Comment by durandguru** [comment]
Almost all the errors are gone in 1.0.11.

Still got this one on routeros_bridge_port
 Warning: Field not found
│
│   with routeros_bridge_port.ether1,
│   on ports.tf line 11, in resource "routeros_bridge_port" "ether1":
│   11: resource "routeros_bridge_port" "ether1" {
│
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: root_path_cost <<<= 10

**Comment by durandguru** [comment]
These messages are gone ;-)
