### ISSUE TITLE
Bridge and STP

### ISSUE THREAD

**Issue by durandguru** [GNewbury1/terraform-provider-routeros#109]
**Describe the bug**
I set STP to RSTP and use priority's. During Plan or apply I get an error about MikrotikResourceDataToTerraform

**To Reproduce**
resource "routeros_bridge" "bridge" {
  name              = "bridge"
  ingress_filtering = true
  protocol_mode     = "rstp"
  priority          = "0x3000"
  igmp_snooping     = true
  vlan_filtering    = true
}

**Additional context**
│ Warning: Field not found
│
│   with routeros_bridge_port.sfp-sfpplus1,
│   on ports.tf line 88, in resource "routeros_bridge_port" "sfp-sfpplus1":
│   88: resource "routeros_bridge_port" "sfp-sfpplus1" {
│
│ [MikrotikResourceDataToTerraform] The field was lost during the Schema development: designated_bridge <<<=
│ 0x2000.2C:C8:1B:05:76:BF

**Comment by vaerh** [comment]
@durandguru Please check the fixes [v1.0.7](https://github.com/GNewbury1/terraform-provider-routeros/releases/tag/v1.0.7)

**Comment by durandguru** [comment]
I do not get the errors anymore in 1.0.8 ;-)
