### ISSUE TITLE
Add ability to manage IPv4 NAT settings

### ISSUE THREAD

**Issue by GNewbury1** [GNewbury1/terraform-provider-routeros#29]
Implement `/ip/firewall/nat` settings.

**Comment by sekwah41** [comment]
This would be great to add as it is the main part I would need for forwarding the services on the network.

**Comment by scotch16** [comment]
I need this too - Creating a pull request with this feature completed.

**Comment by GNewbury1** [comment]
Hi @scotch16 and @sekwah41 - this should have been implemented when vaerh's fork was merged. Can you check and report back, please? https://registry.terraform.io/providers/GNewbury1/routeros/latest/docs/resources/firewall_nat

**Comment by sekwah41** [comment]
I don't have access to anything routeros atm so I cannot verify for now.
