### ISSUE TITLE
Datasources that return array contain wrong values

### ISSUE THREAD

**Issue by deveth0** [GNewbury1/terraform-provider-routeros#47]
**Describe the bug**
I setup a RouterOS with two addresses (*1 and *2, using 10.0.9.1/24 and 192.168.88.1/24), the REST api also returns the correct values.

Using the terraform provider, the list contains the same address twice and is missing the first one. When I create a third address, the array contains three times the last one.

This is also reproducable for the interfaces and routes datasource.

```
ip_addresses = {
  "addresses" = tolist([
    {
      "actual_interface" = "ether1"
      "address" = "192.168.88.1/24"
      "disabled" = true
      "dynamic" = false
      "id" = "*2"
      "interface" = "ether1"
      "invalid" = false
      "network" = "192.168.88.0"
    },
    {
      "actual_interface" = "ether1"
      "address" = "192.168.88.1/24"
      "disabled" = true
      "dynamic" = false
      "id" = "*2"
      "interface" = "ether1"
      "invalid" = false
      "network" = "192.168.88.0"
    },
  ])
  "id" = "terraform-20220120102446891700000001"
}

``` 

**To Reproduce**
Setup multiple routes, addresses or interfaces and query those.

Minimal terraform example:

```
provider "routeros" {
  hosturl  = "https://10.0.9.150"
  username = "admin"
  password = ""
  insecure = true
}

data "routeros_interfaces" "interfaces" {}

data "routeros_ip_routes" "routes" {}

data "routeros_ip_addresses" "addresses" {}


output "interfaces" {
  value = data.routeros_interfaces.interfaces
}

output "ip_addresses" {
  value = data.routeros_ip_addresses.addresses
}

output "routes" {
  value = data.routeros_ip_routes.routes
}


```

**Expected behavior**
Array with the correct entries.

**Comment by deveth0** [comment]
Please find fix attached :)

**Comment by GNewbury1** [comment]
Fantastic, thank you for this report and pull request! It has successfully passed tests, so I'll put it in release 0.3.2
