### ISSUE TITLE
Problem getting it to work

### ISSUE THREAD

**Issue by durandguru** [GNewbury1/terraform-provider-routeros#57]
**Describe the bug**
I want to play around with the provider and I am testing and can't get it to work. Get an Provider produced inconsistent result after apply error (see below). Testing on RouterOS 7.4. Is this a bug or do I do something wrong?

**To Reproduce**
I created a simple file:
terraform {
  required_providers {
    routeros = {
      source = "GNewbury1/routeros"
    }
  }
}

provider "routeros" {
  hosturl  = "https://10.252.10.1"
  username = "abc"
  password = "appeltaart"
  insecure = true
}

resource "routeros_ip_pool" "pool" {
    name   = "my_ip_pool"
    ranges = "10.0.0.100-10.0.0.200"
}

**Expected behavior**
It works..

**Stack Trace**
If applicable, add the stack trace the crash produced.

**Additional context**
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # routeros_ip_pool.pool will be created
  + resource "routeros_ip_pool" "pool" {
      + id     = (known after apply)
      + name   = "my_ip_pool"
      + ranges = "10.0.0.100-10.0.0.200"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

routeros_ip_pool.pool: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to routeros_ip_pool.pool, provider "provider[\"registry.terraform.io/gnewbury1/routeros\"]"
│ produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by GNewbury1** [comment]
I've not been able to replicate this using Terraform 1.3.3 and provider version 0.3.2 with RouterOS 7.5. Unfortunately, I don't have anything still running 7.4 to test with, and 7.6 has now been released. Is this still an issue for you?

**Comment by JanNemcik** [comment]
> I've not been able to replicate this using Terraform 1.3.3 and provider version 0.3.2 with RouterOS 7.5. Unfortunately, I don't have anything still running 7.4 to test with, and 7.6 has now been released. Is this still an issue for you?

I'm using Terraform 1.3.3, RouterOS 7.5 and getting the same error as @durandguru but for wireguard and bridge interface

**Comment by JanNemcik** [comment]
Was able to resolve the problem. As stated in [docs,](https://help.mikrotik.com/docs/display/ROS/REST+API) for REST API to work you need to enable _www-ssl_ service. Enabling itself is not sufficient though (at least wasn't in my case), I also needed to generate and sign certificate and assign it to the _www-ssl_ service. Hope this helps!

**Comment by GNewbury1** [comment]
Ah, I hadn't even thought of that. I'll add a note to the readme in case others run in to this! I'll close this issue for now, but if it turns out to be something else, feel free to ping me and reopen it
