### ISSUE TITLE
Firewall filter rules order

### ISSUE THREAD

**Issue by MischaBoender** [GNewbury1/terraform-provider-routeros#90]
Is there any way to make sure firewall filter rules are in a specific order? So when adding a new rule I can make sure it's added at the top, or just before the final drop rule?

**Comment by vaerh** [comment]
This functionality was implemented using the standard [place_before](https://github.com/GNewbury1/terraform-provider-routeros/blob/main/docs/resources/firewall_filter.md) property. But it needs to be tested!
[See example](https://github.com/GNewbury1/terraform-provider-routeros/blob/main/examples/data-sources/routeros_firewall/data-source.tf)

**Comment by MischaBoender** [comment]
Little bit of a puzzle to determine in which order to create firewall rules to make use of this, but it does work!
