### ISSUE TITLE
Need to check the pull request #97

### ISSUE THREAD

**Issue by vaerh** [GNewbury1/terraform-provider-routeros#99]
Information in the comment https://github.com/GNewbury1/terraform-provider-routeros/commit/60f84e8929d386549a2faadd1d940f78abfbbcb1#commitcomment-100757500

**Comment by GNewbury1** [comment]
Hey @vaerh - I replied to your comment https://github.com/GNewbury1/terraform-provider-routeros/commit/60f84e8929d386549a2faadd1d940f78abfbbcb1#commitcomment-100775877
